//
// Standard Color Indexes for the 666 palette
//
//  D_color is a DARK color
//  B_color is a BRIGHT color
//  L_color is a LIGHT color
//

#define PURPLE  191
#define ORANGE   17
#define YELLOW   35
#define TAN      94
#define BROWN    51

//#define BLACK   0
#define BLACK   216
#define GREY_1   43
#define GREY_2   86
#define GREY_3  129
#define GREY_4  172
#define WHITE   215

#define GREY_SCALE_0  216
#define GREY_SCALE_1  217
#define GREY_SCALE_2  218
#define GREY_SCALE_3  219
#define GREY_SCALE_4  220
#define GREY_SCALE_5  221
#define GREY_SCALE_6  222
#define GREY_SCALE_7  223
#define GREY_SCALE_8  224
#define GREY_SCALE_9  225
#define GREY_SCALE_10 226
#define GREY_SCALE_11 227
#define GREY_SCALE_12 228
#define GREY_SCALE_13 229
#define GREY_SCALE_14 230
#define GREY_SCALE_15 231

#define B_RED     5
#define RED       4
#define D_RED     3
#define B_GREEN  30
#define GREEN    18
#define D_GREEN  48
#define B_BLUE  212
#define L_BLUE  156
#define BLUE    181
#define D_BLUE  144


