//
// Index's into the GUG_key_table[] array
//  1 = indicates key is down
//  0 = indicates key is up
//

//
// General Defines
//
#define KEY_IS_DOWN    1
#define KEY_IS_UP      0

//
// Main keyboard
//					 
#define LEFT_CTRL       29
#define	RIGHT_CTRL      97
#define LEFT_ALT        56
#define RIGHT_ALT       96
#define LEFT_SHIFT      42
#define RIGHT_SHIFT     54
#define SPACE           57
#define TILDE           41
#define KEY_1            2
#define KEY_2            3
#define KEY_3            4
#define KEY_4            5
#define KEY_5            6
#define KEY_6            7
#define KEY_7	         8
#define KEY_8	         9
#define KEY_9     	    10
#define KEY_0    	    11
#define KEY_MINUS       12
#define KEY_EQUAL       13
#define KEY_BS          14
#define KEY_TAB         15
#define KEY_Q		    16
#define KEY_W		    17
#define KEY_E		    18
#define KEY_R		    19
#define KEY_T		    20
#define KEY_Y		    21
#define KEY_U		    22
#define KEY_I		    23
#define KEY_O		    24
#define KEY_P		    25
#define KEY_OPEN_BRACE      26
#define KEY_CLOSE_BRACE     27
#define KEY_RETURN      28
#define KEY_CAPS        29
#define KEY_A		    30
#define KEY_S		    31
#define KEY_D		    32
#define KEY_F		    33
#define KEY_G		    34
#define KEY_H		    35
#define KEY_J		    36
#define KEY_K		    37
#define KEY_L		    38
#define KEY_SEMICOLON   39
#define KEY_QUOTE       40
#define KEY_Z		    44
#define KEY_X		    45
#define KEY_C		    46
#define KEY_V		    47
#define KEY_B		    48
#define KEY_N		    49
#define KEY_M		    50
#define KEY_COMMA	    51
#define KEY_PERIOD	    52
#define KEY_BSLASH	    53
#define KEY_FSLASH	    43
#define KEY_MACRO       86
//
// Cursor Keys
//
#define LEFT_ARROW      99
#define RIGHT_ARROW    100
#define UP_ARROW        98
#define DOWN_ARROW     101
//					 
// Other Cursor Keys
//
#define KEY_INSERT     102
#define KEY_HOME	   103
#define KEY_PAGE_UP	   104
#define KEY_DELETE	   105
#define KEY_END		   106
#define KEY_PAGE_DOWN  107
//
// Numeric Keypad
//
#define LEFT_NUM        75
#define RIGHT_NUM       77
#define UP_NUM          72
#define DOWN_NUM        80
#define NUM_LOCK        69
#define NUM_FSLASH     109 
#define NUM_STAR        55
#define NUM_MINUS       74
#define NUM_7		    71
#define NUM_8   		72
#define NUM_9		    73
#define NUM_4		    75
#define NUM_5		    76
#define NUM_6		    77
#define NUM_PLUS	    78
#define NUM_1		    79
#define NUM_2		    80
#define NUM_3		    81
#define NUM_0		    82
#define NUM_DEL		    83
#define NUM_ENTER      110
//
// Function keys
//
#define F1              59
#define F2              60
#define F3              61
#define F4              62
#define F5              63
#define F6              64
#define F7              65 
#define F8              66
#define F9              67
#define F10             68
#define F11             87
#define F12             88
//
// Other Keys
//
#define ESC              1
#define KEY_SCROLL_LOCK 70
