#define GUG320X200 0  // Default Mode
#define GUG640X480 1
#define GUG800x600 2

#define MAX_SPRITE_X 320	// Max Allowed Screen X Size
#define MAX_SPRITE_Y 200	// Max Allowed Screen Y Size
#define MAX_X_SIZE   320    // Max Sprite X Size
#define MAX_Y_SIZE   200	// Max Sprite Y Size
#define X_WRAP_SIZE (MAX_SPRITE_X     + MAX_X_SIZE)
#define Y_WRAP_SIZE ((MAX_SPRITE_Y*2) + MAX_Y_SIZE)

#define TRANSPARENT 0
