cd blue
call gugasm B5X10_A
call gugasm B6X8_A
call gugasm B4X6_A
call gug    B6X8_C
call gug    B4X6_C
call gug    B5X10_C
call gug    BLUE

cd ..\green
call gugasm G5X10_A
call gugasm G6X8_A
call gugasm G4X6_A
call gug    G6X8_C
call gug    G4X6_C
call gug    G5X10_C
call gug    GREEN

cd ..\red
call gugasm R5X10_A
call gugasm R6X8_A
call gugasm R4X6_A
call gug    R6X8_C
call gug    R4X6_C
call gug    R5X10_C
call gug    RED

cd ..\yellow
call gugasm Y5X10_A
call gugasm Y6X8_A
call gugasm Y4X6_A
call gug    Y6X8_C
call gug    Y4X6_C
call gug    Y5X10_C
call gug    YELLOW

cd ..\orange
call gugasm O5X10_A
call gugasm O6X8_A
call gugasm O4X6_A
call gug    O6X8_C
call gug    O4X6_C
call gug    O5X10_C
call gug    ORANGE

cd ..\white
call gugasm W5X10_A
call gugasm W6X8_A
call gugasm W4X6_A
call gug    W6X8_C
call gug    W4X6_C
call gug    W5X10_C
call gug    WHITE

cd ..

