// Patch compiler
// Written by Eric Jorgensen
//
//  This program takes a config file and compiles all the patches
// listed in it into a single file containing all the patches and info
// on which Midi instruments they represent
//
// Here is example code on how to dereference a file generated by this
// program:
/*
void loadpatches(char *filename)
{
	char errstring[256],string[1000];
	int i,j,ptotal,totalmem,usedmem;
	FILE *input;
	PATCHSAMPLE *psamp;
	BYTE patchmap[256][20];
	PATCH *patchlist[256];
	BYTE *mempointer;
	int readmem = 0;
																	// Zero out patch list
	for(i = 0; i < 256; i++) patchlist[i] = NULL;
																	// Get handle to compiled patch file
	input = fopen(filename,"rb");
	if(!input) {
		verbosef("Error opening patch input file: %s\n",filename);
		return;
	}
																	// Read in and verify ID string
	verbosef("Reading patches...\n");

	if(fread(string,1,40,input) < 40) {
		fclose(input);
		verbosef("File Read error!\n");
		return;
	}
	if(!strstr(string,"FLABBERGASTED Music Goop")) {
		fclose(input);
		verbosef("Not a Music Goop file!\n");
		return;
	}
																	// Ask how much memory we need, then
																	// attempt to allocate it.
	if(fread(&usedmem,1,sizeof(int),input) < sizeof(int)) {
		fclose(input);
		verbosef("File Read error!\n");
		return;
	}

	patchmemory = flabmalloc(usedmem);
	if(!patchmemory) {
		fclose(input);
		verbosef("Out of memory!\n");
		return;
	}
																	// Read the file in by chunks until
																	// we have it all.
	mempointer = (BYTE *)patchmemory;
	while(readmem < usedmem) {
		verbosef(".");
		if(fread(mempointer+readmem,1,50000,input) < 50000) break;
		readmem += 50000;
	}


	verbosef("  Patches loaded into raw memory.  Processing...\n");

																	// Load the patchmap.  The number of
																	// patched in the file is contained in
																	// the very last variable of the patchmap.
	memcpy(patchmap,patchmemory,5120);
	ptotal = patchmap[255][19];
	verbosef("Ptotal = %d\n",ptotal);

																	// Walk through the memory and set up
																	// patch pointers.
	mempointer = (BYTE *)patchmemory + 5120;
	for(i = 0; i < ptotal; i++) {
																	// Point to patch struct
		patchlist[i] = (PATCH *)mempointer;
		mempointer += sizeof(PATCH);
		verbosef("Processing Instrument %s.\n",patchlist[i]->name);

																	// Point to first sample
		patchlist[i]->samplelist = (PATCHSAMPLE *)mempointer;
		mempointer += sizeof(PATCHSAMPLE);

		psamp = patchlist[i]->samplelist;
		psamp->data = (SAMPLE *)mempointer;
		mempointer += psamp->size;
																	// process any additional samples
		while(psamp->next) {
			psamp->next = (PATCHSAMPLE *)mempointer;
			mempointer += sizeof(PATCHSAMPLE);
			psamp = psamp->next;
			psamp->data = (SAMPLE *)mempointer;
			mempointer += psamp->size;
		}
																		// Tell VAT about the new patch
		for(j = 0; j < 20; j++) {
			if(patchmap[i][j] < 128) {
				MidiSetInstrumentPatch(patchmap[i][j],patchlist[i]);
			}
			else if(patchmap[i][j] < 255) {
				MidiSetPercussionPatch(patchmap[i][j]-128,patchlist[i]);
			}

		}
	}

	fclose(input);


}


*/

#include "vat.h"
#include "compat.h"
#include <stdio.h>
#include <conio.h>
#include <dos.h>
#include <malloc.h>
#include <graph.h>
#include <string.h>
#include <ctype.h>

int loadpatches(char *listfile);


PATCH *patchlist[256];
BYTE patchmap[256][20];

/**************************************************************************
	void main(int argc, char *argv[])

	DESCRIPTION:

**************************************************************************/
void main(int argc, char *argv[])
{
	char errstring[256],string[1000];
	int i,j,ptotal,totalmem,usedmem;
	void *zoop;
	FILE *output;
	PATCHSAMPLE *psamp;
																		// Clear the patch table
	for(i = 0; i < 256; i++) {
		patchlist[i] = NULL;
		for(j = 0; j < 20; j++) {
			patchmap[i][j] = 255;
		}
	}
																		// Malloc a big chunk of memory
																		// so that we can track it.
	zoop = malloc(8000000);
	free(zoop);
	totalmem =  _memavl();
	printf("MEMORY: %d bytes\n",totalmem);
																		// load the patch list
	ptotal = loadpatches(argv[1]);
	if(!ptotal) exit(1);
																		// Find memory usage
	usedmem = totalmem - _memavl();
	printf("MEMORY USED: %d bytes\n",usedmem);
	usedmem += 5120;

	getch();
																		// Get a handle to an output file
	if(argc>2) output = fopen(argv[2],"wb");
	else output = fopen("patglob.pts","wb");
	if(!output) {
		printf("Error opening output file...\n");
		exit(1);
	}

	printf("Writing header...\n");
																		 // Put number of patches in last ptable entree
	patchmap[255][19] = ptotal;
																		 // ID string.  40 characters
	sprintf(string,"FLABBERGASTED Music Goop (tm) 1998.01%c",26);

																		// Write out the header which
																		// consists of an ID string, the
																		// ammount of memory used, and the
																		// patchmap
	if(fwrite(string,1,40,output) < 40) { fclose(output); printf("File write error!\n"); exit(-1);}
	if(fwrite(&usedmem,1,sizeof(int),output) < sizeof(int)) { fclose(output); printf("File write error!\n"); exit(-1);}
	if(fwrite(patchmap,1,5120,output) < 5120) { fclose(output); printf("File write error!\n"); exit(-1);}
																		// Binary dump all the patches.
	for(i = 0; i < ptotal; i++) {
		printf("Writing Instrument %s...\n",patchlist[i]->name);
		if(fwrite(patchlist[i],1,sizeof(PATCH),output) < sizeof(PATCH)) { fclose(output); printf("File write error!\n"); exit(-1);}
		psamp = patchlist[i]->samplelist;
		while(psamp) {
			if(fwrite(psamp,1,sizeof(PATCHSAMPLE),output) < sizeof(PATCHSAMPLE)) { fclose(output); printf("File write error!\n"); exit(-1);}
			if(fwrite(psamp->data,1,psamp->size,output) < psamp->size) { fclose(output); printf("File write error!\n"); exit(-1);}
			psamp = psamp->next;
		}
		FreePatch(patchlist[i]);
	}

	fclose(output);

}

/**************************************************************************
	void loadpatches(char *listfile)

	DESCRIPTION:

**************************************************************************/
int loadpatches(char *listfile)
{
	int i;
	FILE *input;
	char filename[1000],string[1000];
	char errstring[256];
	char *spot;
	int flag=1;
	char r;
	int ptotal = 0;
	int mapspot,mindex;

	printf("Loading Patches from %s...\n",listfile);

	input = fopen(listfile,"r");
	if(!input) {
		printf("ERROR:  could not open patch config file: %s\n",listfile);
		getch();
		return ptotal;
	}
																	// Load all the patches
	while(fgets(string,999,input)) {
		spot = strtok(string, " \t");
		strcpy(filename,spot);

		if(isalnum(filename[0]) || filename[0] == '\\') {
			printf("Loading Patch %s... ",filename);
			patchlist[ptotal] = LoadPatch(filename,errstring);
			if(!patchlist[ptotal]) {
				printf(errstring);
			}
			else {
				printf("Success.");
				spot = strtok(NULL, " \t");
				mindex = 0;
				while(spot) {
					sscanf(spot,"%d",&mapspot);
					if(isdigit(*spot)) {
						patchmap[ptotal][mindex++] = mapspot;
						printf("%d ",mapspot);
					}
					spot = strtok(NULL, " \t");

				}
				ptotal++;
			}
			printf("\n");
		}
	}

	if(!ptotal) printf("No patch files loaded. \n");

	return ptotal;
}
