#
# GUG "c" test makefile
#

# The demo program
test.exe : test.c ship_a.obj ship_c.obj 
  wcl386 -c -l=dos4g test.c
  wlink @link.cmd

# A compiled ship sprite from spr2asm
ship_a.obj : ship_a.asm
  wasm ship_a.asm
ship_c.obj : ship_c.c
  wcl386 -c -l=causeway ship_c.c
